# Generated by Django 5.2.16 on 2026-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Nom')),
                ('tech_type', models.CharField(choices=[('language', 'Langage'), ('framework', 'Framework'), ('database', 'Base de données'), ('middleware', 'Middleware'), ('os', "Système d'exploitation"), ('cloud', 'Cloud / SaaS'), ('tool', 'Outil'), ('other', 'Autre')], db_index=True, default='other', max_length=32, verbose_name='Type')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name', 'version'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_technology_name_version')],
            },
        ),
    ]
