# Generated by Django 5.2.16 on 2026-07-31 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('env_type', models.CharField(choices=[('dev', 'DEV'), ('recette', 'RECETTE'), ('preprod', 'PREPROD'), ('prod', 'PROD')], db_index=True, max_length=16, verbose_name="Type d'environnement")),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('os', models.CharField(blank=True, max_length=128, verbose_name="Système d'exploitation")),
                ('cpu', models.CharField(blank=True, max_length=64, verbose_name='CPU')),
                ('ram', models.CharField(blank=True, max_length=64, verbose_name='RAM')),
                ('hosting_provider', models.CharField(blank=True, max_length=255, verbose_name='Hébergeur')),
                ('docker', models.BooleanField(default=False, verbose_name='Docker')),
                ('kubernetes', models.BooleanField(default=False, verbose_name='Kubernetes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='applications.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Environnement',
                'verbose_name_plural': 'Environnements',
                'ordering': ['application__name', 'env_type'],
                'constraints': [models.UniqueConstraint(fields=('application', 'env_type'), name='uniq_application_env_type')],
            },
        ),
    ]
