# Generated by Django 5.2.16 on 2026-08-07 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_perf_indexes'),
        ('contracts', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_deleted', 'is_active', 'end_date'], name='contract_active_end_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_deleted', 'status'], name='contract_deleted_status_idx'),
        ),
    ]
