# Generated by Django 5.2.16 on 2026-08-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dependency_type', models.CharField(choices=[('api', 'API'), ('base_donnees', 'Base de données'), ('fichier', 'Fichier / batch'), ('message', 'Messagerie'), ('auth', 'Authentification'), ('autre', 'Autre')], db_index=True, default='api', max_length=32, verbose_name='Type de dépendance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_external', models.CharField(blank=True, help_text='Ex. Active Directory, PostgreSQL, API tierce…', max_length=255, verbose_name='Cible externe')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('source_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_out', to='applications.application', verbose_name='Application source')),
                ('target_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_in', to='applications.application', verbose_name='Application cible')),
            ],
            options={
                'verbose_name': 'Dépendance applicative',
                'verbose_name_plural': 'Dépendances applicatives',
                'ordering': ['source_application__name', 'dependency_type'],
            },
        ),
    ]
