# Generated by Django 5.2.16 on 2026-08-04 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descriptor', models.JSONField()),
                ('enrolled_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identifiant facial',
                'verbose_name_plural': 'Identifiants faciaux',
            },
        ),
    ]
