# Generated by Django 5.2.16 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_facecredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur DSI'), ('dsi', 'Administrateur DSI (DSI)'), ('manager', 'Équipe DSI / Technicien'), ('viewer', 'Lecteur')], db_index=True, default='viewer', max_length=32),
        ),
    ]
