# Generated by Django 5.2.16 on 2026-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_perf_indexes'),
        ('certificates', '0002_initial'),
        ('domains', '0002_domain_auto_renew'),
        ('environments', '0002_environment_server'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_deleted', 'is_active', 'expires_at'], name='cert_active_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_deleted', 'status'], name='cert_deleted_status_idx'),
        ),
    ]
