# Generated by Django 5.2.16 on 2026-08-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Nom du fichier')),
                ('file_type', models.CharField(blank=True, max_length=64, verbose_name='Type de fichier')),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('manuel_utilisateur', 'Manuel utilisateur'), ('manuel_exploitation', 'Manuel exploitation'), ('contrat', 'Contrat'), ('procedure', 'Procédure')], db_index=True, default='architecture', max_length=32, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'upload")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application', verbose_name='Application')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='documents.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
    ]
