# Generated by Django 5.2.16 on 2026-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nom')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Adresse IP')),
                ('os', models.CharField(blank=True, max_length=128, verbose_name="Système d'exploitation")),
                ('cpu', models.CharField(blank=True, max_length=64, verbose_name='CPU')),
                ('ram', models.CharField(blank=True, max_length=64, verbose_name='RAM')),
                ('datacenter', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Datacenter')),
                ('server_type', models.CharField(choices=[('physical', 'Physique'), ('vm', 'VM'), ('cloud', 'Cloud')], db_index=True, default='vm', max_length=16, verbose_name='Type de serveur')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
                'ordering': ['name'],
            },
        ),
    ]
