# Generated by Django 5.2.16 on 2026-08-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname agent')),
                ('cpu_percent', models.FloatField(verbose_name='CPU %')),
                ('memory_total', models.BigIntegerField(verbose_name='RAM totale (octets)')),
                ('memory_used', models.BigIntegerField(verbose_name='RAM utilisée (octets)')),
                ('memory_percent', models.FloatField(verbose_name='RAM %')),
                ('disk_total', models.BigIntegerField(verbose_name='Disque total (octets)')),
                ('disk_used', models.BigIntegerField(verbose_name='Disque utilisé (octets)')),
                ('disk_percent', models.FloatField(verbose_name='Disque %')),
                ('net_bytes_sent', models.BigIntegerField(default=0, verbose_name='Réseau envoyé (octets)')),
                ('net_bytes_recv', models.BigIntegerField(default=0, verbose_name='Réseau reçu (octets)')),
                ('load_avg_1', models.FloatField(default=0, verbose_name='Load average 1 min')),
                ('uptime_seconds', models.FloatField(default=0, verbose_name='Uptime (secondes)')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Collecté le')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.server', verbose_name='Serveur')),
            ],
            options={
                'verbose_name': 'Métrique serveur',
                'verbose_name_plural': 'Métriques serveurs',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['server', '-collected_at'], name='servers_ser_server__0ae22f_idx')],
            },
        ),
    ]
