# Generated by Django 5.2.16 on 2026-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_add_servermetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier ping'),
        ),
        migrations.AddField(
            model_name='server',
            name='ping_status',
            field=models.CharField(choices=[('unknown', 'Inconnu'), ('up', 'En ligne'), ('down', 'Hors ligne')], db_index=True, default='unknown', max_length=16, verbose_name='Statut Ping'),
        ),
    ]
