# Generated by Django 5.2.16 on 2026-07-31 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('criticality', models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], db_index=True, default='medium', max_length=32, verbose_name='Criticité')),
                ('status', models.CharField(choices=[('project', 'En projet'), ('production', 'En production'), ('maintenance', 'En maintenance'), ('deprecated', 'Obsolète'), ('retired', 'Retirée')], db_index=True, default='project', max_length=32, verbose_name='Statut')),
                ('go_live_date', models.DateField(blank=True, null=True, verbose_name='Date de mise en production')),
                ('end_of_life_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de vie')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisateurs")),
                ('business_unit', models.CharField(blank=True, max_length=255, verbose_name='Direction métier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('technologies', models.ManyToManyField(blank=True, related_name='applications', to='technologies.technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
    ]
