# Generated by Django 5.2.16 on 2026-08-07 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_deleted', 'status'], name='app_deleted_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_deleted', 'criticality'], name='app_deleted_crit_idx'),
        ),
    ]
