# Generated by Django 5.2.16 on 2026-08-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Action')),
                ('entity', models.CharField(db_index=True, max_length=64, verbose_name='Entité')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID entité')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-occurred_at'],
            },
        ),
    ]
