# Generated by Django 5.2.16 on 2026-08-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name="Date de l'incident")),
                ('impact', models.CharField(choices=[('critique', 'Critique'), ('majeur', 'Majeur'), ('mineur', 'Mineur'), ('faible', 'Faible')], db_index=True, default='majeur', max_length=32, verbose_name='Impact')),
                ('root_cause', models.TextField(blank=True, verbose_name='Cause racine')),
                ('solution', models.TextField(blank=True, verbose_name='Solution')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('clos', 'Clos')], db_index=True, default='ouvert', max_length=32, verbose_name='Statut')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='applications.application', verbose_name='Application')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-occurred_at', 'title'],
            },
        ),
    ]
