# Generated by Django 5.2.16 on 2026-08-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('expiration', 'Expiration'), ('incident', 'Incident'), ('systeme', 'Système')], db_index=True, default='info', max_length=32, verbose_name='Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'envoi")),
                ('status', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue'), ('archivee', 'Archivée')], db_index=True, default='non_lue', max_length=32, verbose_name='Statut')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Lien relatif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
