# Generated by Django 5.2.16 on 2026-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_days_60', models.PositiveSmallIntegerField(default=60, help_text='Bande d’alerte anticipée (ex. 60 jours avant échéance).', verbose_name='Seuil alerte J-60 (jours)')),
                ('alert_days_30', models.PositiveSmallIntegerField(default=30, help_text='Bande d’alerte rapprochée (ex. 30 jours avant échéance).', verbose_name='Seuil alerte J-30 (jours)')),
                ('alert_on_expiry', models.BooleanField(default=True, verbose_name='Alerte le jour d’expiration (J-0)')),
                ('alert_cooldown_days', models.PositiveSmallIntegerField(default=7, help_text='Ne pas renvoyer la même alerte (ressource + seuil) avant N jours.', verbose_name='Délai anti-doublon (jours)')),
            ],
            options={
                'verbose_name': 'Paramètres plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
    ]
